// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tinhchisoMBI.Data;

#nullable disable

namespace tinhchisoMBI.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    [Migration("20250417083703_AllowNullForDonHang1")]
    partial class AllowNullForDonHang1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tinhchisoMBI.Models.chisoBMI", b =>
                {
                    b.Property<string>("Ten")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("BMI")
                        .HasColumnType("float");

                    b.Property<double>("CanNang")
                        .HasColumnType("float");

                    b.Property<double>("ChieuCao")
                        .HasColumnType("float");

                    b.Property<int>("DiemA")
                        .HasColumnType("int");

                    b.Property<int>("DiemB")
                        .HasColumnType("int");

                    b.Property<int>("DiemC")
                        .HasColumnType("int");

                    b.Property<double?>("DiemTong")
                        .HasColumnType("float");

                    b.Property<string>("DonHang1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonHang2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DonHang3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TongTien")
                        .HasColumnType("float");

                    b.Property<int>("Tuoi")
                        .HasColumnType("int");

                    b.HasKey("Ten");

                    b.ToTable("chisoBMI");
                });
#pragma warning restore 612, 618
        }
    }
}
