// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tinhchisoMBI.Data;

#nullable disable

namespace tinhchisoMBI.Migrations
{
    [DbContext(typeof(ApplicationDbcontext))]
    [Migration("20250411070849_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("tinhchisoMBI.Models.Person", b =>
                {
                    b.Property<string>("Ten")
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("BMI")
                        .HasColumnType("REAL");

                    b.Property<double>("CanNang")
                        .HasColumnType("REAL");

                    b.Property<double>("ChieuCao")
                        .HasColumnType("REAL");

                    b.Property<int>("DiemA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiemB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiemC")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DiemTong")
                        .HasColumnType("REAL");

                    b.Property<string>("DonHang1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DonHang2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DonHang3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("TongTien")
                        .HasColumnType("REAL");

                    b.Property<int>("Tuoi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Ten");

                    b.ToTable("Persons");
                });
#pragma warning restore 612, 618
        }
    }
}
